name: SAST scan
on:
  push:
    branches: ['master']
  pull_request: 
  
jobs:
  build:
  
  sca-scan:
    runs-on: ubuntu-22.04
    permissions: 
      contents: read
      security-events: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6.2.0

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run SAST
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: 'repo'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL, HIGH, MEDIUM'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
        
