name: Build and run unit tests
on:
  push:
    branches: ['master']
  pull_request: 
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and save the docker image
        run: |
          docker build -t vulpy:${{github.sha}} .
          docker save vulpy:${{github.sha}} -o image.tar 
      
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: vulpy-docker-image
          path: image.tar

  tests:
    runs-on: ubuntu-slim
    steps:
      - name: Run the tests
        run: echo "Running tests..."
        
